Feature/calculator
dev-White-team/WhiteBot pull request #42
Opened 2022-03-01 12:47 UTC by froggal

문구 수정했습니다. 자세한건 커밋 메시지 참고해주세요

2022-03-01 13:02 UTC, nkgcp requested changes
린트 액션 로그 확인하셔서 스타일 오류도 해결해주시면 되겠습니다.

2022-03-01 13:02 UTC, nkgcp commented on functions/calc.py
> +            title="<a:check:824251178493411368> 계산 완료!",
![Screenshot_20220301-215339_Discord.png](https://user-images.githubusercontent.com/65478530/156173284-267628e1-8c3f-486b-beb2-d0e62d54a799.png)

제목에 이모지가 들어가지 않습니다.
제거하는 것이 좋아보입니다.

2022-03-02 04:33 UTC, froggal commented on functions/calc.py
> +        second: Option(str, "연산할 두 번째 수를 입력하세요"),
알겠습니다. int 함수를 이용해서 수정하겠습니다

2022-03-02 04:34 UTC, froggal commented on functions/calc.py
> +            title="<a:check:824251178493411368> 계산 완료!",
왜 안들어갈까요?

2022-03-02 05:26 UTC, nkgcp commented on functions/calc.py
> +            title="<a:check:824251178493411368> 계산 완료!",
커스텀 이모지는 임베드 타이틀에 넣을 수 없습니다.

2022-03-05 03:36 UTC, Whitetiger0423 commented on functions/calc.py
> +            title="<a:check:824251178493411368> 계산 완료!",
커스텀 이모지도 임베드 타이틀에 넣을 수 있습니다 - 베타봇으로 테스트한뒤 불가능하다면 그때 바꾸도록 하겠습니다.

2022-03-05 03:40 UTC, Whitetiger0423 commented on functions/calc.py
> +            title="<a:check:824251178493411368> 계산 완료!",
정상작동하네요.

2022-03-05 10:53 UTC, HydrOxy2gen commented
```
 embed = discord.Embed(
            title = "WhiteBot 오류", description="주사위 기능", color=0xFF0000
            )
            embed.add_field(
                name="오류 내용:",
                value="숫자를 입력해주세요",
                inline=False,
            )
```

위 embed 문구에서 이 코드는 계산 기능을 위한 코드이기 때문에 description에 '주사위 기능' 대신 '계산 기능'이 쓰이는 것이 올바르다고 생각됩니다.

2022-03-05 13:42 UTC, froggal commented
> 

앗 맞습니다 ! 제가 미처 확닌을 못 했군요..

2022-03-05 15:10 UTC, Whitetiger0423 submitted a review, later dismissed

2022-03-05 15:25 UTC, nkgcp approved these changes
정상작동 확인

2022-03-05 15:31 UTC, nkgcp approved these changes

2022-03-05 15:32 UTC, merged